# Generated by Django 4.0 on 2021-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100, verbose_name='Tarefa')),
                ('dia', models.DateField(max_length=11, verbose_name='Dia')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
    ]
