# Generated by Django 4.0 on 2021-12-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_categoria_remove_tarefa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria'),
        ),
    ]
