# Generated by Django 4.0 on 2021-12-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tarefa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'pendente'), ('Concluída', 'concluída'), ('Adiada', 'adiada')], default='Pendente', max_length=30),
        ),
    ]
