# Generated by Django 4.0 on 2021-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Adiada', 'Adiada')], default='Pendente', max_length=30),
        ),
    ]
