# Generated by Django 4.0 on 2022-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='dia',
            field=models.DateField(verbose_name='Dia'),
        ),
    ]
