# Generated by Django 4.0 on 2022-01-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tarefa_dia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
