# Generated by Django 4.0 on 2022-01-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Trabalho', 'Trabalho'), ('Escola', 'Escola'), ('Contas', 'Contas')], max_length=30, verbose_name='Categoria'),
        ),
    ]
