# Generated by Django 4.0 on 2022-01-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Trabalho', 'Trabalho'), ('Escola', 'Escola'), ('Contas', 'Contas')], max_length=50, verbose_name='Categoria'),
        ),
    ]
