# Generated by Django 4.0 on 2022-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_categoria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='dia',
            field=models.DateTimeField(verbose_name='Dia'),
        ),
    ]
